import { api, API_BASE_URL } from "./api.js";

const state = { view: "dashboard", files: [], blocks: [], chain: null, selectedFile: null, selectedRecovery: null, selectedVerification: null, selectedReport: null, filter: "", busy: false };
const viewRoot = document.querySelector("#viewRoot");
const pageNames = { dashboard: ["Overview", "Dashboard"], files: ["Workspace", "Evidence files"], erasure: ["Operations", "Secure erasure"], recovery: ["Operations", "File recovery"], verification: ["Integrity", "Verification"], ledger: ["Integrity", "Audit ledger"], audit: ["Integrity", "Audit trail"], reports: ["Evidence", "Reports"] };

const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const formatDate = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not available";
const formatBytes = (bytes) => { if (bytes === undefined || bytes === null) return "Not available"; if (!bytes) return "0 B"; const units = ["B", "KB", "MB", "GB"]; const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / (1024 ** index)).toFixed(index ? 1 : 0)} ${units[index]}`; };
const shortHash = (value, length = 16) => value ? `${value.slice(0, length)}…` : "Not available";
const badge = (value) => { const normalized = String(value || "unknown").toUpperCase(); const className = ["MISMATCH", "FAILED", "INVALID"].includes(normalized) ? "bad" : ["PENDING", "NOT_AVAILABLE", "UPLOADED"].includes(normalized) ? "warn" : ""; return `<span class="badge ${className}">${escapeHtml(normalized.replaceAll("_", " "))}</span>`; };
const emptyState = (title, message) => `<div class="empty-state"><strong>${escapeHtml(title)}</strong><span>${escapeHtml(message)}</span></div>`;
const loading = (message = "Loading evidence") => `<div class="loading-line"><span class="spin">◌</span>${escapeHtml(message)}…</div>`;

function notify(message, type = "success") { const item = document.createElement("div"); item.className = `toast ${type === "error" ? "error" : type === "warning" ? "warning" : ""}`; item.textContent = message; document.querySelector("#toastRegion").append(item); window.setTimeout(() => item.remove(), 5200); }
function setBusy(button, busy, label) { if (!button) return; button.disabled = busy; if (busy) { button.dataset.label = button.textContent; button.innerHTML = `<span class="spin">◌</span>${label || "Working"}`; } else if (button.dataset.label) button.textContent = button.dataset.label; }
function renderShell() { const [section, page] = pageNames[state.view]; document.querySelector("#crumbSection").textContent = section; document.querySelector("#crumbPage").textContent = page; document.querySelectorAll(".nav-item").forEach((item) => item.classList.toggle("active", item.dataset.view === state.view)); }

async function loadGlobalData() { const [files, blocks, chain] = await Promise.all([api.listFiles(), api.listBlocks(), api.verifyChain()]); state.files = files.items || []; state.blocks = blocks.blocks || []; state.chain = chain; document.querySelector("#apiStatus").textContent = "API connected"; }

function statCard(label, value, foot) { return `<article class="stat-card"><div class="stat-label">${label}</div><div class="stat-number">${value}</div><div class="stat-foot">${foot}</div></article>`; }
function activityRows() { const events = state.blocks.slice(-5).reverse(); if (!events.length) return emptyState("No activity yet", "Upload evidence to begin the chain."); return `<div class="activity-list">${events.map((block) => `<div class="activity-row"><span class="activity-symbol">${block.action === "erasure" ? "⌁" : block.action === "verification" ? "✓" : block.action === "file_carving_scan" ? "⌗" : "•"}</span><div><strong>${escapeHtml(block.action.replaceAll("_", " "))}</strong><small>${escapeHtml(shortHash(block.file_id, 18))} · block ${block.block_index}</small></div><span class="activity-time">${formatDate(block.timestamp)}</span></div>`).join("")}</div>`; }
function dashboardView() { const processed = state.files.filter((file) => ["erased", "uploaded"].includes(file.status)).length; const erasures = state.blocks.filter((block) => block.action === "erasure").length; const recoveries = state.blocks.filter((block) => block.action === "file_carving_scan").length; const verified = state.blocks.filter((block) => block.action === "verification").length; return `<div class="page-intro"><div><div class="eyebrow">FORENSIC OPERATIONS / 01</div><h1>Evidence console</h1><p>Monitor controlled evidence, integrity operations, and the local tamper-evident chain from one workspace.</p></div><div class="intro-mark">${state.chain?.valid ? "● CHAIN VERIFIED" : "○ CHAIN CHECK REQUIRED"}</div></div><div class="stat-grid">${statCard("Registered evidence", state.files.length, "Files in controlled storage")}${statCard("Processed files", processed, "Uploaded or completed")}${statCard("Erasure operations", erasures, "Recorded on ledger")}${statCard("Recovery operations", recoveries, "Carving scans recorded")}</div><div class="dashboard-grid"><section class="panel"><div class="panel-header"><div><h2>Recent activity</h2><p>Latest blocks appended to the local audit ledger</p></div><button class="button text" data-navigate="ledger">View ledger →</button></div>${activityRows()}</section><section class="panel chain-card"><div class="panel-header"><div><h2>Chain integrity</h2><p>Recalculated against stored hashes</p></div>${badge(state.chain?.valid ? "VERIFIED" : "INVALID")}</div><div class="chain-visual"><span class="chain-node">${state.blocks.length ? "B0" : "—"}</span><span class="chain-line"></span><span class="chain-node">${state.blocks.length > 1 ? `B${state.blocks.length - 1}` : "—"}</span><span class="chain-line"></span><span class="chain-node">SHA</span></div><div class="chain-result"><span>Blocks recorded</span><strong>${state.blocks.length}</strong></div><div class="chain-result"><span>Invalid blocks</span><strong>${state.chain?.invalid_blocks?.length || 0}</strong></div></section></div>`; }

function filesView() { const filtered = state.files.filter((file) => `${file.original_filename} ${file.file_id} ${file.status}`.toLowerCase().includes(state.filter.toLowerCase())); return `<div class="page-intro"><div><div class="eyebrow">CONTROLLED STORAGE / 02</div><h1>Evidence files</h1><p>Every uploaded item is hashed, registered, audited, and linked to the local ledger.</p></div></div><div class="form-layout">${uploadPanel("upload")}<section class="panel"><div class="panel-header"><div><h2>Operation guide</h2><p>Choose a registered file below for the next action.</p></div></div><div class="result-card"><div class="result-row"><span>Upload</span><span>Hash + audit + block</span></div><div class="result-row"><span>Erasure</span><span>Overwrite + certificate</span></div><div class="result-row"><span>Recovery</span><span>Upload sample, then carve</span></div><button class="button secondary full-width" data-navigate="erasure">Open erasure workspace</button></div></section></div><section class="panel" style="margin-top:18px"><div class="toolbar"><input class="search-input" id="fileSearch" placeholder="Search filename, ID, status" value="${escapeHtml(state.filter)}"><span class="eyebrow">${state.files.length} REGISTERED ITEMS</span></div>${filtered.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>File</th><th>Type / size</th><th>SHA-256</th><th>Uploaded</th><th>Status</th><th>Action</th></tr></thead><tbody>${filtered.map((file) => `<tr><td><strong>${escapeHtml(file.original_filename)}</strong><div class="mono">${escapeHtml(shortHash(file.file_id, 18))}</div></td><td>${escapeHtml(file.file_type || "Not available")}<br>${formatBytes(file.file_size)}</td><td class="mono" title="${escapeHtml(file.original_hash)}">${escapeHtml(shortHash(file.original_hash))}</td><td>${formatDate(file.upload_timestamp)}</td><td>${badge(file.status)}</td><td><button class="button secondary small" data-select-file="${escapeHtml(file.file_id)}">Use file</button></td></tr>`).join("")}</tbody></table></div>` : emptyState("No evidence files", "Upload a controlled file to populate this workspace.")}</section>`; }

function uploadPanel(kind = "upload") { const isRecovery = kind === "recovery"; return `<section class="panel form-panel"><div class="panel-header"><div><h2>${isRecovery ? "Controlled sample" : "Register evidence"}</h2><p>${isRecovery ? "Upload a sample binary first, then scan it for supported signatures." : "The backend calculates SHA-256 and creates the first audit records."}</p></div></div><div class="dropzone" id="dropzone"><div><div class="drop-icon">⇧</div><h3>Drop a file here</h3><p>or choose a file from your device</p><label class="button secondary" for="filePicker">Choose file</label><input class="file-input" id="filePicker" type="file"></div></div><div id="selectedFile"></div><button class="button primary full-width" id="uploadAction" disabled>${isRecovery ? "Upload sample" : "Upload and hash evidence"}</button></section>`; }
function uploadHandlers(isRecovery) { const picker = document.querySelector("#filePicker"); const dropzone = document.querySelector("#dropzone"); const selected = document.querySelector("#selectedFile"); const action = document.querySelector("#uploadAction"); let file = null; const select = (next) => { file = next; selected.innerHTML = file ? `<div class="selected-file"><span>◈ ${escapeHtml(file.name)}</span><small>${formatBytes(file.size)}</small></div>` : ""; action.disabled = !file; }; picker.addEventListener("change", () => select(picker.files[0])); ["dragenter", "dragover"].forEach((event) => dropzone.addEventListener(event, (e) => { e.preventDefault(); dropzone.classList.add("dragging"); })); ["dragleave", "drop"].forEach((event) => dropzone.addEventListener(event, (e) => { e.preventDefault(); dropzone.classList.remove("dragging"); })); dropzone.addEventListener("drop", (e) => select(e.dataTransfer.files[0])); action.addEventListener("click", async () => { setBusy(action, true, isRecovery ? "Uploading" : "Hashing"); try { const uploaded = await api.uploadFile(file); state.files = [uploaded, ...state.files.filter((item) => item.file_id !== uploaded.file_id)]; if (isRecovery) { const result = await api.scanRecovery(uploaded.file_id); state.selectedRecovery = result; notify(`Recovery scan complete: ${result.number_of_files_detected} file(s) detected`); render(); } else { notify("Evidence uploaded, hashed, and recorded on the ledger"); state.selectedFile = uploaded; render(); } } catch (error) { notify(error.message, "error"); setBusy(action, false); } }); }

function erasureView() { const file = state.selectedFile; return `<div class="page-intro"><div><div class="eyebrow">SANITIZATION / 03</div><h1>Secure erasure</h1><p>Confirm a controlled file, verify its original hash, then produce an auditable erasure certificate.</p></div></div><div class="form-layout">${file ? `<section class="panel form-panel"><div class="panel-header"><div><h2>Selected evidence</h2><p>Ready for prototype overwrite and deletion</p></div>${badge(file.status)}</div><div class="result-card"><div class="result-row"><span>Filename</span><span>${escapeHtml(file.original_filename)}</span></div><div class="result-row"><span>File ID</span><span class="mono">${escapeHtml(file.file_id)}</span></div><div class="result-row"><span>Original SHA-256</span><span class="mono">${escapeHtml(file.original_hash)}</span></div><div class="result-row"><span>Size</span><span>${formatBytes(file.file_size)}</span></div><div class="result-row"><span>Method</span><span>overwrite_then_delete</span></div></div><button class="button danger full-width" id="eraseAction" ${file.status === "erased" ? "disabled" : ""}>Confirm secure erasure</button></section>` : `<section class="panel form-panel">${emptyState("No file selected", "Choose an evidence file from the file workspace before erasing.")}<button class="button primary full-width" data-navigate="files">Choose evidence file</button></section>`}<section class="panel"><div class="panel-header"><div><h2>Operation result</h2><p>Certificate details appear after the backend confirms completion.</p></div></div>${state.selectedFile?.certificate ? certificateMarkup(state.selectedFile.certificate) : emptyState("Awaiting operation", "No erasure certificate has been returned for this session.")}</section></div>`; }
function certificateMarkup(certificate) { return `<div class="result-card"><div class="result-row"><span>Certificate ID</span><span class="mono">${escapeHtml(certificate.certificate_id)}</span></div><div class="result-row"><span>Status</span><span>${badge(certificate.status)}</span></div><div class="result-row"><span>Timestamp</span><span>${formatDate(certificate.timestamp)}</span></div><div class="result-row"><span>Original hash</span><span class="mono">${escapeHtml(certificate.original_hash)}</span></div><button class="button secondary full-width" data-navigate="reports">Open reports workspace</button></div>`; }

function recoveryView() { const recovery = state.selectedRecovery; return `<div class="page-intro"><div><div class="eyebrow">FILE CARVING / 04</div><h1>Recovery lab</h1><p>Upload a controlled sample, scan supported signatures, and inspect hashes plus available metadata.</p></div></div><div class="form-layout">${uploadPanel("recovery")}<section class="panel"><div class="panel-header"><div><h2>Latest scan</h2><p>JPEG, PNG, and PDF signature carvers</p></div>${recovery ? badge(recovery.number_of_files_detected ? "COMPLETED" : "NOT_AVAILABLE") : ""}</div>${recovery ? `<div class="result-card"><div class="result-row"><span>Recovery ID</span><span class="mono">${escapeHtml(recovery.recovery_id)}</span></div><div class="result-row"><span>Files detected</span><span>${recovery.number_of_files_detected}</span></div><div class="result-row"><span>Completed</span><span>${formatDate(recovery.recovery_timestamp)}</span></div></div>` : emptyState("No scan selected", "Upload a controlled sample to begin.")}</section></div>${recovery ? recoveryArtifacts(recovery) : ""}`; }
function recoveryArtifacts(recovery) { if (!recovery.recovered_files?.length) return `<section class="panel" style="margin-top:18px">${emptyState("No recoverable signatures", "The backend completed the scan but found no supported artifacts.")}</section>`; return `<section class="panel" style="margin-top:18px"><div class="panel-header"><div><h2>Recovered artifacts</h2><p>Hashes and metadata returned by the recovery service</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Filename</th><th>Type / size</th><th>SHA-256</th><th>Recovered</th><th>Metadata</th></tr></thead><tbody>${recovery.recovered_files.map((artifact) => `<tr><td><strong>${escapeHtml(artifact.recovered_filename)}</strong><div class="mono">${escapeHtml(shortHash(artifact.recovery_id, 18))}</div></td><td>${escapeHtml(artifact.file_type || "Not available")}<br>${formatBytes(artifact.file_size)}</td><td class="mono" title="${escapeHtml(artifact.recovered_hash)}">${escapeHtml(shortHash(artifact.recovered_hash))}</td><td>${formatDate(artifact.recovery_timestamp)}</td><td><button class="button secondary small" data-metadata='${escapeHtml(JSON.stringify(artifact.metadata_info || {}))}'>Inspect</button></td></tr>`).join("")}</tbody></table></div></section>`; }

function verificationView() { const result = state.selectedVerification; return `<div class="page-intro"><div><div class="eyebrow">INTEGRITY / 05</div><h1>Verification</h1><p>Compare registered source hashes and recovered artifact hashes against the controlled storage state.</p></div></div><div class="panel form-panel"><label class="field-label" for="verificationFile">Evidence file</label><select class="select-input full-width" id="verificationFile"><option value="">Select a registered file</option>${state.files.map((file) => `<option value="${escapeHtml(file.file_id)}" ${result?.file_id === file.file_id ? "selected" : ""}>${escapeHtml(file.original_filename)} · ${escapeHtml(shortHash(file.file_id, 12))}</option>`).join("")}</select><button class="button primary" id="verifyAction" style="margin-top:15px" disabled>Run verification</button></div>${result ? `<section class="panel" style="margin-top:18px"><div class="panel-header"><div><h2>Verification result</h2><p>${formatDate(result.verification_timestamp)}</p></div>${badge(result.comparison_result)}</div><div class="detail-grid"><div class="detail-block"><label>Stored / original hash</label><div class="mono">${escapeHtml(result.original_hash || "Not available")}</div></div><div class="detail-block"><label>Current hash</label><div class="mono">${escapeHtml(result.current_hash || "Not available")}</div></div><div class="detail-block"><label>Algorithm</label><div>${escapeHtml(result.hash_algorithm)}</div></div><div class="detail-block"><label>Operation</label><div class="mono">${escapeHtml(result.related_operation.operation_id)}</div></div></div>${result.recovered_hashes?.length ? `<h3 style="font-size:13px;margin:26px 0 8px">Recovered hashes</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Artifact</th><th>Stored hash</th><th>Current hash</th><th>Status</th></tr></thead><tbody>${result.recovered_hashes.map((item) => `<tr><td>${escapeHtml(item.recovered_filename)}</td><td class="mono">${escapeHtml(shortHash(item.stored_hash))}</td><td class="mono">${escapeHtml(shortHash(item.current_hash))}</td><td>${badge(item.status)}</td></tr>`).join("")}</tbody></table></div>` : ""}</section>` : ""}`; }

function ledgerView() { return `<div class="page-intro"><div><div class="eyebrow">TAMPER EVIDENCE / 06</div><h1>Audit ledger</h1><p>A local blockchain-style ledger. Every block below is returned by the backend and linked by hash.</p></div><button class="button secondary" id="chainVerifyAction">Verify chain</button></div><section class="panel"><div class="panel-header"><div><h2>Chain status</h2><p>${state.chain?.total_blocks || 0} blocks recalculated</p></div>${badge(state.chain?.valid ? "VERIFIED" : "INVALID")}</div>${state.blocks.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Index</th><th>Action</th><th>Timestamp</th><th>File ID</th><th>Previous hash</th><th>Current hash</th></tr></thead><tbody>${state.blocks.map((block) => `<tr><td class="mono">#${block.block_index}</td><td>${badge(block.action)}</td><td>${formatDate(block.timestamp)}</td><td class="mono">${escapeHtml(shortHash(block.file_id, 16))}</td><td class="mono">${escapeHtml(shortHash(block.previous_hash))}</td><td class="mono">${escapeHtml(shortHash(block.current_hash))}</td></tr>`).join("")}</tbody></table></div>` : emptyState("Ledger is empty", "Upload evidence to append the first block.")}</section>`; }
function auditView() { const file = state.selectedFile; return `<div class="page-intro"><div><div class="eyebrow">CHAINED EVENTS / 07</div><h1>Audit trail</h1><p>Inspect chronological events tied to one registered evidence file.</p></div></div><div class="panel form-panel"><label class="field-label" for="auditFile">Evidence file</label><select class="select-input full-width" id="auditFile"><option value="">Select a registered file</option>${state.files.map((item) => `<option value="${escapeHtml(item.file_id)}" ${file?.file_id === item.file_id ? "selected" : ""}>${escapeHtml(item.original_filename)} · ${escapeHtml(shortHash(item.file_id, 12))}</option>`).join("")}</select><button class="button primary" id="auditAction" style="margin-top:15px" disabled>Load audit trail</button></div>${file?.audit ? `<section class="panel" style="margin-top:18px"><div class="panel-header"><div><h2>${file.audit.total_events} recorded events</h2><p>Chronological audit records for ${escapeHtml(file.original_filename)}</p></div></div><div class="timeline">${file.audit.events.map((event) => `<div class="timeline-item"><div class="timeline-rail"></div><div class="timeline-content"><h3>${escapeHtml(event.action)} ${badge(event.status)}</h3><p>${formatDate(event.timestamp)} · block ${event.blockchain_block_index ?? "Not linked"}</p><div class="detail-grid" style="margin-top:14px"><div class="detail-block"><label>Audit ID</label><div class="mono">${escapeHtml(event.audit_id)}</div></div><div class="detail-block"><label>Hash</label><div class="mono">${escapeHtml(shortHash(event.hash, 22))}</div></div></div></div></div>`).join("")}</div></section>` : ""}`; }
function reportsView() { const report = state.selectedReport; return `<div class="page-intro"><div><div class="eyebrow">DOCUMENTATION / 08</div><h1>Reports & certificates</h1><p>Generate a backend report from recorded erasure or recovery evidence and download the resulting JSON.</p></div></div><div class="panel form-panel"><label class="field-label" for="reportFile">Evidence file</label><select class="select-input full-width" id="reportFile"><option value="">Select a registered file</option>${state.files.map((file) => `<option value="${escapeHtml(file.file_id)}" ${report?.file_id === file.file_id ? "selected" : ""}>${escapeHtml(file.original_filename)} · ${escapeHtml(shortHash(file.file_id, 12))}</option>`).join("")}</select><button class="button primary" id="reportAction" style="margin-top:15px" disabled>Generate report</button></div>${report ? `<section class="panel" style="margin-top:18px"><div class="panel-header"><div><h2>Report generated</h2><p>${formatDate(report.generated_at)}</p></div><a class="button secondary" href="${api.reportDownloadUrl(report.file_id)}" target="_blank" rel="noreferrer">Download JSON</a></div><div class="detail-grid"><div class="detail-block"><label>Report path</label><div class="mono">${escapeHtml(report.report_path)}</div></div><div class="detail-block"><label>Blockchain references</label><div>${report.blockchain_audit_references.length}</div></div><div class="detail-block"><label>Erasure certificate</label><div>${report.erasure_certificate ? badge("AVAILABLE") : "Not available"}</div></div><div class="detail-block"><label>Recovery reports</label><div>${report.recovery_reports.length}</div></div></div></section>` : ""}`; }

function render() { renderShell(); const views = { dashboard: dashboardView, files: filesView, erasure: erasureView, recovery: recoveryView, verification: verificationView, ledger: ledgerView, audit: auditView, reports: reportsView }; viewRoot.innerHTML = views[state.view](); bindView(); }
function bindView() { document.querySelectorAll("[data-navigate]").forEach((button) => button.addEventListener("click", () => navigate(button.dataset.navigate))); document.querySelectorAll("[data-select-file]").forEach((button) => button.addEventListener("click", () => { state.selectedFile = state.files.find((file) => file.file_id === button.dataset.selectFile); navigate("erasure"); })); document.querySelector("#fileSearch")?.addEventListener("input", (event) => { state.filter = event.target.value; render(); }); if (state.view === "files") uploadHandlers(false); if (state.view === "recovery") uploadHandlers(true); if (state.view === "erasure") bindErasure(); if (state.view === "verification") bindVerification(); if (state.view === "audit") bindAudit(); if (state.view === "reports") bindReports(); if (state.view === "ledger") document.querySelector("#chainVerifyAction")?.addEventListener("click", verifyChain); document.querySelectorAll("[data-metadata]").forEach((button) => button.addEventListener("click", () => { const metadata = JSON.parse(button.dataset.metadata); notify(JSON.stringify(metadata, null, 2), "warning"); })); }
function bindErasure() { document.querySelector("#eraseAction")?.addEventListener("click", () => { const file = state.selectedFile; document.querySelector("#confirmText").textContent = `This will overwrite and delete “${file.original_filename}”. The backend will record an irreversible erasure operation.`; document.querySelector("#confirmModal").classList.remove("hidden"); document.querySelector("#confirmAction").onclick = async () => { const action = document.querySelector("#confirmAction"); setBusy(action, true, "Erasing"); try { const certificate = await api.eraseFile(file.file_id); state.selectedFile = { ...file, status: "erased", certificate }; state.files = state.files.map((item) => item.file_id === file.file_id ? state.selectedFile : item); document.querySelector("#confirmModal").classList.add("hidden"); notify("Secure erasure completed and certificate recorded"); await loadGlobalData(); render(); } catch (error) { notify(error.message, "error"); setBusy(action, false); } }; }); }
function bindVerification() { const select = document.querySelector("#verificationFile"); const action = document.querySelector("#verifyAction"); select?.addEventListener("change", () => { action.disabled = !select.value; }); action?.addEventListener("click", async () => { setBusy(action, true, "Verifying"); try { state.selectedVerification = await api.verifyFile(select.value); notify(`Verification result: ${state.selectedVerification.comparison_result}`); await loadGlobalData(); render(); } catch (error) { notify(error.message, "error"); setBusy(action, false); } }); }
function bindAudit() { const select = document.querySelector("#auditFile"); const action = document.querySelector("#auditAction"); select?.addEventListener("change", () => { action.disabled = !select.value; }); action?.addEventListener("click", async () => { setBusy(action, true, "Loading"); try { const file = state.files.find((item) => item.file_id === select.value); state.selectedFile = { ...file, audit: await api.auditTrail(select.value) }; notify("Audit trail loaded"); render(); } catch (error) { notify(error.message, "error"); setBusy(action, false); } }); }
function bindReports() { const select = document.querySelector("#reportFile"); const action = document.querySelector("#reportAction"); select?.addEventListener("change", () => { action.disabled = !select.value; }); action?.addEventListener("click", async () => { setBusy(action, true, "Generating"); try { state.selectedReport = await api.report(select.value); notify("Report generated by the backend"); await loadGlobalData(); render(); } catch (error) { notify(error.message, "error"); setBusy(action, false); } }); }
async function verifyChain() { try { state.chain = await api.verifyChain(); render(); notify(state.chain.valid ? "Chain verified: all links are intact" : "Chain invalid: inspect the ledger", state.chain.valid ? "success" : "error"); } catch (error) { notify(error.message, "error"); } }
async function navigate(view) { state.view = view; document.querySelector("#sidebar").classList.remove("open"); if (view === "dashboard" || view === "files" || view === "ledger") { viewRoot.innerHTML = loading(); try { await loadGlobalData(); } catch (error) { document.querySelector("#apiStatus").textContent = "API offline"; viewRoot.innerHTML = `<section class="panel">${emptyState("Backend unavailable", error.message)}</section>`; return; } } render(); }

document.querySelectorAll(".nav-item").forEach((item) => item.addEventListener("click", () => navigate(item.dataset.view)));
document.querySelector("#refreshButton").addEventListener("click", () => navigate(state.view));
document.querySelector("#mobileMenu").addEventListener("click", () => document.querySelector("#sidebar").classList.toggle("open"));
document.querySelectorAll("[data-close-modal]").forEach((button) => button.addEventListener("click", () => document.querySelector("#confirmModal").classList.add("hidden")));
document.querySelector("#todayDate").textContent = new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date());

navigate("dashboard");
